# Generated by Django 2.0.5 on 2018-05-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='name',
        ),
        migrations.AddField(
            model_name='animal',
            name='ds_observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='animal',
            name='dt_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='animal',
            name='dt_pegou_cria',
            field=models.DateField(blank=True, null=True, verbose_name='Data Pegou Cria'),
        ),
        migrations.AddField(
            model_name='animal',
            name='dt_venda',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Venda/Morte'),
        ),
        migrations.AddField(
            model_name='animal',
            name='id_cor',
            field=models.IntegerField(blank=True, choices=[(1, 'Branca'), (2, 'Preta'), (3, 'Holandês'), (4, 'Vermelha'), (5, 'Amarela'), (6, 'Fumaça')], null=True, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='animal',
            name='id_mamando',
            field=models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=1, verbose_name='Mamando'),
        ),
        migrations.AddField(
            model_name='animal',
            name='id_sexo',
            field=models.IntegerField(choices=[(0, 'F'), (1, 'M')], default=1, verbose_name='Sexo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='id_situacao',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Vendido'), (3, 'Morreu'), (4, 'Terc. Ativo'), (5, 'Terc. Inativo')], default=1, verbose_name='Situação'),
        ),
        migrations.AddField(
            model_name='animal',
            name='nm_animal',
            field=models.CharField(default='Teste', max_length=30, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='vl_venda',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor de Venda'),
        ),
    ]
