# Generated by Django 2.0.5 on 2018-05-28 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animais', '0002_auto_20180528_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='cd_animal_mae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mae', to='animais.Animal', verbose_name='Mãe'),
        ),
        migrations.AddField(
            model_name='animal',
            name='cd_animal_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pai', to='animais.Animal', verbose_name='Pai'),
        ),
        migrations.AddField(
            model_name='animal',
            name='cd_pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Dono'),
        ),
        migrations.AddField(
            model_name='animal',
            name='cd_touro_pegou_cria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marido', to='animais.Animal', verbose_name='Touro Pegou Cria'),
        ),
    ]
