# Generated by Django 2.0.5 on 2018-05-28 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_auto_20180528_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='cd_animal_mae',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_sexo': 0}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mae', to='animais.Animal', verbose_name='Mãe'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='cd_animal_pai',
            field=models.ForeignKey(blank=True, limit_choices_to={'id_sexo': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pai', to='animais.Animal', verbose_name='Pai'),
        ),
    ]
