# Generated by Django 2.0.5 on 2018-05-29 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
                ('valor', models.FloatField()),
                ('vencimento', models.DateField()),
                ('pagamento', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='tipo',
            name='codigo_bb',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código BB'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='tipo',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_pai': None}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipo', to='caixa.Tipo'),
        ),
    ]
