# Generated by Django 2.0.5 on 2018-05-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='nome',
            field=models.CharField(max_length=80),
        ),
    ]
